# Generated by Django 4.1.7 on 2023-03-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_dismissal_venue_battingperformance_out"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="innings",
            options={"verbose_name_plural": "innings"},
        ),
        migrations.AddField(
            model_name="match",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="venues",
                to="games.venue",
            ),
        ),
    ]
