# Generated by Django 4.1.7 on 2023-03-23 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_alter_innings_options_match_venue"),
    ]

    operations = [
        migrations.AddField(
            model_name="battingperformance",
            name="how_out",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="games.dismissal",
            ),
        ),
        migrations.AlterField(
            model_name="battingperformance",
            name="out",
            field=models.BooleanField(default=1),
        ),
    ]
