# Generated by Django 4.1.7 on 2023-03-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_battingperformance_how_out_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bowlingperformance",
            name="no_balls",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bowlingperformance",
            name="wides",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="innings",
            name="byes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="innings",
            name="leg_byes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bowlingperformance",
            name="runs_conceded",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bowlingperformance",
            name="wickets",
            field=models.IntegerField(default=0),
        ),
    ]
