# Generated by Django 4.1.7 on 2023-03-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0005_bowlingperformance_no_balls_bowlingperformance_wides_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bowlingperformance",
            name="dots",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bowlingperformance",
            name="fours",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bowlingperformance",
            name="sixes",
            field=models.IntegerField(default=0),
        ),
    ]
