# Generated by Django 4.1.7 on 2023-03-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0007_alter_match_options_battingperformance_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="battingperformance",
            options={"ordering": ("created",)},
        ),
        migrations.AlterModelOptions(
            name="bowlingperformance",
            options={"ordering": ("created",)},
        ),
        migrations.AlterModelOptions(
            name="dismissal",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="innings",
            options={"ordering": ("-created",), "verbose_name_plural": "innings"},
        ),
        migrations.AlterModelOptions(
            name="match",
            options={"ordering": ("-created",), "verbose_name_plural": "matches"},
        ),
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ("name", "team")},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="venue",
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="battingperformance",
            name="batted_at",
            field=models.CharField(
                choices=[
                    (0, 0),
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=0,
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="bowlingperformance",
            name="bowled_at",
            field=models.CharField(
                choices=[
                    (0, 0),
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=1,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="battingperformance",
            name="balls_faced",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="battingperformance",
            name="fours",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="battingperformance",
            name="runs",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="battingperformance",
            name="sixes",
            field=models.IntegerField(default=0),
        ),
    ]
